name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '23.x'

    - name: Install dependencies
      run: npm install

    - name: Run ESLint
      run: npm run lint -- --fix

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.12.0
      with:
        mongodb-version: '6.0.18'  
        mongodb-replica-set: test-rs
        mongodb-port: 27017

    - name: Run Tests
      run: npm test

    - name: Start Server (Optional)
      run: node server.js &

    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'  # Ensures deploy only happens from main branch
      uses: JamesIves/github-pages-deploy-action@4.2.1
      with:
        branch: gh-pages  
        folder: ./build   
        token: ${{ secrets.GITHUB_TOKEN }}
