name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '23.x'

    - name: Install dependencies
      run: npm install

    - name: Run ESLint
      run: npm run lint -- --fix

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.12.0
      with:
        mongodb-version: '6.0.18'
        mongodb-replica-set: test-rs
        mongodb-port: 27017

    - name: Run Tests
      run: npm test

    - name: Start Server (Optional)
      run: node server.js &

    - name: Generate static files (Build)
      run: npm run build  

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.2.1
      with:
        branch: gh-pages
        folder: ./build
        clean: true
        token: ${{ secrets.GH_TOKEN }}  # Reference the token secret here

    - name: Notify on success
      run: echo "Deployment to GitHub Pages successful!"
